INSERT INTO reg_regencies (id, province_id, name) VALUES ('9301', '93', 'Kabupaten Merauke');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9302', '93', 'Kabupaten Boven Digoel');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9303', '93', 'Kabupaten Mappi');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9304', '93', 'Kabupaten Asmat');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9401', '94', 'Kabupaten Nabire');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9402', '94', 'Kabupaten Puncak Jaya');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9403', '94', 'Kabupaten Paniai');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9404', '94', 'Kabupaten Mimika');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9405', '94', 'Kabupaten Puncak');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9406', '94', 'Kabupaten Dogiyai');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9407', '94', 'Kabupaten Intan Jaya');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9408', '94', 'Kabupaten Deiyai');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9501', '95', 'Kabupaten Jayawijaya');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9502', '95', 'Kab Pegunungan Bintang');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9503', '95', 'Kabupaten Yahukimo');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9504', '95', 'Kabupaten Tolikara');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9505', '95', 'Kabupaten Mamberamo Tengah');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9506', '95', 'Kabupaten Yalimo');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9507', '95', 'Kabupaten Lanny Jaya');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9508', '95', 'Kabupaten Nduga');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9601', '96', 'Kabupaten Sorong');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9602', '96', 'Kabupaten Sorong Selatan');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9603', '96', 'Kabupaten Raja Ampat');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9604', '96', 'Kabupaten Tambrauw');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9605', '96', 'Kabupaten Maybrat');
INSERT INTO reg_regencies (id, province_id, name) VALUES ('9671', '96', 'Kota Sorong');